version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]  # skip major bumps

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
