version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]  # skip major bumps

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
